lesson_step.lesson_step_entity_type.*:
  type: config_entity
  label: 'Lesson Step type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
